spring:
  application:
    name: kanri
  mvc:
    servlet:
      path: /api/v1
  datasource:
    url: jdbc:postgresql://db:5432/kanri_system
    username: kanrisys
    password: kanrisys
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
jwt:
  secret: your256bitsecretkeyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
  expiration: 86400000 # 24 hours (milliseconds)