server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  application:
    name: kanri
  datasource:
    url: jdbc:postgresql://db:5432/kanri_system
    username: kanri_sys
    password: kanri_sys
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      continue-on-error: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql: trace

jwt:
  secret: "SGVsbG8gSmF2YSBJc2FueG9vbCBUaGlzIHNlY3JldCBLZXkgZm9yIEpXVCAoMjU2IGJpdCBTZWN1cmUp"
  expiration: 3600000   # 1h (ms)